
##### Epi parameters: means 
# case type distribution
q_A: 0.36 # asymptomatic
q_Im: 0.6 # mild
q_Is: 0.04 # severe

# among severe: proportion going to H/Hbar stream (vs. nursing homes or prisons)
# the value of 1 corresponds to a community transmission model
q_H: 1 

# transmissibility
beta_pre: 1.2

# latency
delta: 0.25   # 1/4

## FOI
# FOI from Asymptomatic in the absence of testing
alpha_A: 0.1428571   # 1/7 (infectious for 7 days)
k_A: 0.4 # relative infectiousness of asymptomatic compared to mildly symptomatic

# FOI from Mild
alpha_Im: 0.25   # 1/4 (infectious for 4 days, then isolated)

# FOI from Severe
alpha_Is: 0.1052632    # 1/9.5 (9.5 days between end of latency and hospitalization, 13.5 between infection and hosp)
k_Is: 0.7        # some severe cases are likely isolated sooner than 9.5 days after infection onset
                 # but probably more infectious at the beginning 

## Severe
# length of hospital stay
gamma_H: 0.11   # 1/8.8
gamma_Hbar: 0.11   

# remaining time until recovery or death, nursing homes
gamma_NH: 0.073  # 1/14 

## Mild : duration of isolation
# replace with an estimate of duration of PCR detectable virus rather than duration of infectiousness
gamma_NI: 0.1428571 # 1/7 (10 days from symptom onset - 3 days in I_m state)

## CFR
m_H: 0.2 # among hospitalized
m_NH_mult: 1.4 # RR among severe in nursing homes / prisons
m_Hbar_mult: 1.5 # RR among hospital overflow

# other
k_n: 0.015 # transmission from adjacent counties

# reporting lags (days)
H_lag: 5
D_lag: 5
detect_lag: 7

# initial number exposed on (day0 - time_num)
E_init: 35

# time point from candidate_state0 that becomes state0
time_num: 14

# main lockdown effect on log scale
lockdown_effect: -1.7

# school reopening effect on log scale
school_reopening_effect: 0.2

# intervention effect on isolation/recovery for A and I_m
# this number times log(daily number of tests) is an increase in the rate of transitioning out of infectious compartment 
testing_effect: 0.03 # corresponds to compartment I_m
te_A_mult: 0.5 # relative testing effect among A compared to I_m



# standard deviations, lower and upper bounds 
# of model parameters for uncertainty in projections
#sd_beta_pre: 0.05
#lower_beta_pre: 0.6
#upper_beta_pre: 1.4





### not used with the random effects model
# ramping time for lockdown effect
#ramp_time: 1

#school_closure_effect: 0

# post-lockdown
#ph1_release_effect: 0
#ph2_release_effect: 0
#ph3_release_effect: 0



