
##### Epi parameters: means 
# case type distribution
q_A: 0.36 # asymptomatic
q_Im: 0.6 # mild
q_Is: 0.04 # severe

# among severe: proportion going to H/Hbar stream (vs. nursing homes or prisons)
# the value of 1 corresponds to a community transmission model
# when q_H = 1, gamma_NH and m_NH_mult are ignored
q_H: 1 

# transmissibility
beta_pre: 2

# latency
delta: 0.25   # 1/4

## FOI
# FOI from Asymptomatic in the absence of testing
alpha_A: 0.1428571   # 1/7 (infectious for 7 days)
k_A: 0.4 # relative infectiousness of asymptomatic compared to mildly symptomatic

# FOI from Mild
alpha_Im: 0.25   # 1/4 (infectious for 4 days, then isolated)

# FOI from Severe
alpha_Is: 0.08333333    # 1/12 (12 days between end of latency and hospitalization)
k_Is: 1        

## Severe
# length of hospital stay
gamma_H: 0.12   # replaced with hdischarge function
gamma_Hbar: 0.12   # same

## Mild : duration of isolation
# replace with an estimate of duration of PCR detectable virus rather than duration of infectiousness?
gamma_NI: 0.1428571 # 1/7 (10 days from symptom onset - 3 days in I_m state)

## CFR
m_H: 0.12 # baseline, among hospitalized from community
m_Hbar_mult: 1 # RR among hospital overflow

# reporting lags (days)
H_lag: 5
D_lag: 5
detect_lag: 7

# initial number exposed on (day0 - time_num)
E_init: 300

# time point from candidate_state0 that becomes state0
time_num: 7

# intervention effect on isolation/recovery for A and I_m
# this number times log(daily number of tests) is an increase in the rate of transitioning out of infectious compartment 
testing_effect: 0.08 # corresponds to compartment I_m
te_A_mult: 0.5 # relative testing effect among A compared to I_m

# hypothetical intervention effect in the future
intv1_effect: 0

# other
k_n: 0.015 # transmission from adjacent counties






# only matter when U (NH) compartment is modelled, i.e. when q_H < 1
# remaining time until recovery or death, nursing homes
gamma_NH: 0.073  # 1/14 
# CFR 
m_NH_mult: 2 # RR among severe in nursing homes / prisons



# standard deviations, lower and upper bounds 
# of model parameters for uncertainty in projections
#sd_beta_pre: 0.05
#lower_beta_pre: 0.6
#upper_beta_pre: 1.4


### not used with the random effects model
# ramping time for lockdown effect
#ramp_time: 1

#school_closure_effect: 0

# post-lockdown
#ph1_release_effect: 0
#ph2_release_effect: 0
#ph3_release_effect: 0

#lockdown_effect: 0
#school_reopening_effect: 0


